# .air.toml for Windows
root = "."
tmp_dir = "tmp"

[build]
  cmd = "templ generate && go build -o ./tmp/main.exe ./app/main.go"
  bin = "tmp/main.exe"
  include_ext = ["go", "templ"]
  exclude_dir = ["assets", "node_modules", "tmp"]
  delay = 1000

[log]
  time = true
